import * as fs from "fs";
import * as path from "path";

const NETWORK_META: Record<string, { name: string; explorer: string }> = {
  "11155111": {
    name: "Sepolia",
    explorer: "https://sepolia.etherscan.io",
  },
  "10200": {
    name: "Chiado",
    explorer: "https://gnosis-chiado.blockscout.com",
  },
  "84532": {
    name: "Base Sepolia",
    explorer: "https://base-sepolia.blockscout.com",
  },
};

interface DeployedAddresses {
  [key: string]: string; // "Module#ContractName" -> address
}

function extractContractName(key: string): string {
  // Format: "ModuleName#ContractName"
  const parts = key.split("#");
  return parts.length > 1 ? parts[1] : parts[0];
}

function findChainDirs(deploymentsDir: string): string[] {
  if (!fs.existsSync(deploymentsDir)) return [];
  return fs
    .readdirSync(deploymentsDir)
    .filter((d) => d.startsWith("chain-") && d !== "chain-31337")
    .map((d) => path.join(deploymentsDir, d));
}

function readDeployedAddresses(chainDir: string): DeployedAddresses | null {
  const filePath = path.join(chainDir, "deployed_addresses.json");
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, "utf-8"));
}

function findArtifact(
  artifactsDir: string,
  contractName: string
): any[] | null {
  // Look for artifacts/contracts/<Name>.sol/<Name>.json
  const artifactPath = path.join(
    artifactsDir,
    "contracts",
    `${contractName}.sol`,
    `${contractName}.json`
  );
  if (!fs.existsSync(artifactPath)) return null;
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
  return artifact.abi || null;
}

function generateDeploymentsMd(
  deployments: Map<string, { contracts: Map<string, string> }>
): string {
  const lines: string[] = [
    "# Deployed Contracts",
    "",
    "> Auto-generated by `scripts/post-deploy.ts` — do not edit manually.",
    "",
  ];

  // Sort chains by name for consistent output
  const sortedChains = [...deployments.entries()].sort((a, b) => {
    const nameA = NETWORK_META[a[0]]?.name || a[0];
    const nameB = NETWORK_META[b[0]]?.name || b[0];
    return nameA.localeCompare(nameB);
  });

  for (const [chainId, { contracts }] of sortedChains) {
    const meta = NETWORK_META[chainId];
    const networkName = meta?.name || `Chain ${chainId}`;
    const explorer = meta?.explorer;

    lines.push(`## ${networkName} (Chain ID: ${chainId})`);
    lines.push("");
    lines.push("| Contract | Address | Explorer |");
    lines.push("|----------|---------|----------|");

    // Sort contracts alphabetically
    const sortedContracts = [...contracts.entries()].sort((a, b) =>
      a[0].localeCompare(b[0])
    );

    for (const [name, address] of sortedContracts) {
      const explorerLink = explorer
        ? `[View](${explorer}/address/${address})`
        : "—";
      lines.push(`| ${name} | \`${address}\` | ${explorerLink} |`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

function writeAbis(
  abisDir: string,
  artifactsDir: string,
  contractNames: Set<string>
): void {
  fs.mkdirSync(abisDir, { recursive: true });

  for (const name of contractNames) {
    const abi = findArtifact(artifactsDir, name);
    if (abi) {
      const outPath = path.join(abisDir, `${name}.json`);
      fs.writeFileSync(outPath, JSON.stringify(abi, null, 2) + "\n");
      console.log(`  ABI: ${outPath}`);
    } else {
      console.warn(`  Warning: artifact not found for ${name}`);
    }
  }
}

async function main() {
  const rootDir = path.resolve(__dirname, "..");
  const deploymentsDir = path.join(rootDir, "ignition", "deployments");
  const artifactsDir = path.join(rootDir, "artifacts");
  const abisDir = path.join(rootDir, "dist", "abis");
  const mdPath = path.join(rootDir, "deployments.md");

  const chainDirs = findChainDirs(deploymentsDir);
  if (chainDirs.length === 0) {
    console.log("No deployments found (ignition/deployments/chain-*).");
    return;
  }

  // Collect all deployments and contract names
  const deployments = new Map<
    string,
    { contracts: Map<string, string> }
  >();
  const allContractNames = new Set<string>();

  for (const chainDir of chainDirs) {
    const chainId = path.basename(chainDir).replace("chain-", "");
    const addresses = readDeployedAddresses(chainDir);
    if (!addresses || Object.keys(addresses).length === 0) continue;

    const contracts = new Map<string, string>();
    for (const [key, address] of Object.entries(addresses)) {
      const name = extractContractName(key);
      contracts.set(name, address);
      allContractNames.add(name);
    }

    deployments.set(chainId, { contracts });
  }

  if (deployments.size === 0) {
    console.log("No deployed contracts found.");
    return;
  }

  // Generate deployments.md
  const md = generateDeploymentsMd(deployments);
  fs.writeFileSync(mdPath, md);
  console.log(`Generated: ${mdPath}`);

  // Write ABI files
  console.log("Extracting ABIs:");
  writeAbis(abisDir, artifactsDir, allContractNames);

  console.log("\nDone.");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
